name: yct_cgpa_calculator
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5 # For value comparison in BLoC states

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # UI & Theming
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0 # For the animations you requested

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7



flutter:
  uses-material-design: true

  assets:
  - assets/yabatech_logo.png
  - assets/yabatech_logo_dark.png


flutter_native_splash:
  # Color is the background
  color: "#FFFBEA" # Cream (for light mode)
  color_dark: "#121212" # Dark grey (for dark mode)

  # Image is the logo
  image: assets/yabatech_logo.png
  image_dark: assets/yabatech_logo_dark.png

  android: true
  ios: true
  web: false